import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "../components/useCont/page";
import { QuizProvider } from "../components/QuizContext/page";
import Cookies from "js-cookie";
import { PlayingQuizProvider } from "../components/PlayingQuizConst/page";
import "@/components/firebase";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
if (Cookies.get("id") && Cookies.get("id") !== undefined) {
}

//-------
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlayingQuizProvider>
          <UserProvider>
            <QuizProvider>{children}</QuizProvider>
          </UserProvider>
        </PlayingQuizProvider>
      </body>
    </html>
  );
}
